site_name: Python Ember Mug
site_url: https://sopelj.github.io/python-ember-mug
repo_url: https://github.com/sopelj/python-ember-mug
repo_name: sopelj/python-ember-mug
watch:
  - ember_mug
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sopelj/python-ember-mug
      name: Github
    - icon: material/email
      link: "mailto:jesse.sopel@gmail.com"
# uncomment the following and put your google tracking id below to enable GA
# google_analytics:
#   - UA-xxx
#   - auto
